### ISSUE TITLE
Decouple from IBM infra

### ISSUE THREAD

**Issue by jlaframboise** [dialogue-planning/contingent-plan-executor#13]
# What
While developing in hovor, I notice that there are some tightly coupled bits with IBM's infrastructure. Working with IBM's infrastructure is beneficial, but should be one of many options. 
# Why
When I was looking  to get hovor running some conversations, I started with locote_main.py which relied on having IBM credentials and using cloudant. This is not something that should be needed to run hovor as a server and send REST requests. 
# How
Abstract the functionality of cloudant and other services, and make them one option out of many. For example, allowing the use of MongoDB or others which can be run locally would be nice.

**Comment by haz** [comment]
@beckydvn Did you already start along this path? I recall us discussing it, but can't recall the outcome.

**Comment by beckydvn** [comment]
Yep, should all be taken care of in `modernize-hovor` :)
