### ISSUE TITLE
Can't import / use hovor

### ISSUE THREAD

**Issue by haz** [dialogue-planning/contingent-plan-executor#17]
Seems as though [this line](https://github.com/dialogue-planning/contingent-plan-executor/blob/184b8c4addc22c6b39e7904813f9c031f5d3d656/contingent_plan_executor/hovor/__init__.py#L27) gets triggered when we're just trying to import hovor stuff (for the simulation things w/ @jlaframboise ).

Any chance you could detail what's going on here, @beckydvn ?

**Comment by beckydvn** [comment]
Ah, for all my stuff when I ran Hovor I needed to be able to access an output files directory (i.e. the generated plan). @jlaframboise does some of your simulated stuff run without accessing some output files? If so I'll shift things around so that's not required:)

**Comment by haz** [comment]
Oh, it likely will. But I don't think we should have much of anything that runs actual code at the top-level of python files. If it's a file we want to invoke, then it's the `if __name__...` stuff we use (like [this](https://github.com/dialogue-planning/contingent-plan-executor/blob/184b8c4addc22c6b39e7904813f9c031f5d3d656/contingent_plan_executor/local_main_simulated.py#L13)). With the code in the __init__.py file there, we can't import anything from hovor without it complaining. So all that code should be in the appropriate methods to set things up, and we'd call those methods with the appropriate parameters as need be.

That make sense? Hard to hand-wave the explanation here in GitHub :P

**Comment by beckydvn** [comment]
That makes sense, I can change that then :)
